apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ms-sql-horizon-b
  namespace: production
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: sc-med-r1-generic
  volumeMode: Filesystem
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 40Gi
  phase: Bound
