apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-sql-horizon-b
spec:
  replicas: 1
  selector:
     matchLabels:
       app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql
        image: microsoft/mssql-server-linux
        ports:
        - containerPort: 1433
          name: tcp1433
          protocol: TCP
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: ''
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      dnsConfig:
        searches:
        - qualcomm.com
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: ms-sql-horizon-b
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-deployment
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer