kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: prometheus-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.org/proxy-connect-timeout: 120s
    nginx.ingress.kubernetes.io/affinity: cookie
spec:
  rules:
  - host: 
    http:
      paths:
      - path:
        backend:
          serviceName: prometheusalert-service
          servicePort: 80
  tls:
  - hosts:
    - 
    secretName: flaskvci
---
kind: Service
apiVersion: v1
metadata:
  name: prometheusalert-service
spec:
  ports:
  - name: app-port
    port: 80
    targetPort: 9093
  selector:
    app: prometheusalert-vci
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: prometheusalert-vci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheusalert-vci
    spec:
      containers:
      - name: prometheusalert-vci
        image: prom/alertmanager
        imagePullPolicy: Always
        ports:
        - containerPort: 9093
    
